[build]
  publish = "dist"

# Serve schemas with proper headers
[[headers]]
  for = "/schema/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/schema+json"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/schema/latest/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/schema+json"
    Cache-Control = "public, max-age=3600"  # Shorter cache for latest

# Schema redirects - allow accessing without .json extension
[[redirects]]
  from = "/schema/:version/:name"
  to = "/schema/:version/:name.json"
  status = 200

# Root redirect to GitHub
[[redirects]]
  from = "/"
  to = "https://github.com/unpunnyfuns/tokens"
  status = 302