name: CI

on:
  push:
    branches:
      - "feat/**"
      - "fix/**"
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  PNPM_VERSION: 10.15.0

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Cache Turbo
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      # Run all CI tasks
      - name: Run CI
        run: pnpm turbo quality test:coverage

      - name: Check for changesets
        if: github.event_name == 'pull_request'
        run: |
          # Skip changeset check for release PRs
          if [[ "${{ github.head_ref }}" == *changeset* ]]; then
            echo "✅ Skipping changeset check for release PR"
            exit 0
          fi
          
          if [ "$(ls -A .changeset/*.md 2>/dev/null | grep -v README | wc -l)" -eq 0 ]; then
            echo "❌ No changesets found. Please run 'pnpm changeset' to create one."
            exit 1
          else
            echo "✅ Changesets found"
          fi

      - name: Upload coverage
        uses: codecov/codecov-action@v4
        if: always()
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
