name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run linting and formatting
        run: npm run check
      
      - name: Check TypeScript
        run: npm run typecheck
      
      - name: Run unit tests
        run: npm run test:run
      
      - name: Validate schemas
        run: npm run dev:schemas
      
      - name: Build schemas (verify they compile)
        run: |
          npm run build:schemas
          echo "✅ Schemas built successfully. Dist files will be generated during release."
      
      - name: Validate examples
        run: npm run validate:examples
        continue-on-error: true  # Known issues with full.schema.json examples