name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run linting
        run: npm run check
      
      - name: Validate schemas
        run: npm run dev:validate-schemas
      
      - name: Build schemas
        run: npm run build:schemas
      
      - name: Check if dist is up to date
        run: |
          if [ -n "$(git status --porcelain dist/)" ]; then
            echo "Error: dist/ is not up to date. Run 'npm run build:schemas' and commit the changes."
            git diff dist/
            exit 1
          fi
      
      - name: Validate examples
        run: npm run validate:examples
        continue-on-error: true  # Known issues with full.schema.json examples