name: Deploy to Netlify

on:
  workflow_dispatch:

env:
  PNPM_VERSION: 10.15.0

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify web schemas exist
        run: |
          # Web schemas should already be built and committed by the release pipeline
          if [ ! -d "libs/schemas/dist-web/schemas" ]; then
            echo "❌ Web schemas not found. Run a release first to build and commit schemas."
            exit 1
          fi
          
          echo "✅ Web schemas found, ready for deployment:"
          ls -la libs/schemas/dist-web/

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: "./libs/schemas/dist-web"
          production-branch: main
          production-deploy: true
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
